#Parameters that need to be changed depending on benchmark
IS_FLATTENED = true
TOP_MODULE 	= b11
CLK_NAME 	= clock
RESET_NAME 	= reset
RESET_EDGE 	= 1
UNROLL_CYC	= 100
TARGET		= 23
OBJ_SRC 	= ./src/b11.v

