#Parameters that need to be changed depending on benchmark
IS_FLATTENED = true
TOP_MODULE 	= top
CLK_NAME 	= clock
RESET_NAME 	= reset
RESET_EDGE 	= 1
UNROLL_CYC	= 10
TARGET		= 0
OBJ_SRC 	= ./src/top.v
