#Parameters that need to be changed depending on benchmark
IS_FLATTENED = true
TOP_MODULE 	= b10
CLK_NAME 	= clock
RESET_NAME 	= reset
RESET_EDGE 	= 1
UNROLL_CYC	= 30
TARGET		= 108
OBJ_SRC 	= ./src/b10.v
